### ISSUE TITLE
Desktop.browseDirectory() does not work properly on Fedora

### ISSUE THREAD

**Issue by kaloyan-raev** [dorkbox/Utilities#3]
I have Fedora 25 with VSCode installed on it.

If, for example, I invoke `Desktop.browseDirectory("/home/user/some-dir")`, it will open an empty file with name `~/git/my-test-app/file:/home/user/some-dir` in VSCode instead of opening `/home/user/some-dir` in the file browser.

I've done some debugging and it seems that the issue is a combination of:
- prepending `file://` to the file path: https://github.com/dorkbox/Utilities/blob/master/src/dorkbox/util/Desktop.java#L175-L182
- opening the directory with `GnomeVFS.gnome_vfs_url_show_with_env()`: https://github.com/dorkbox/Utilities/blob/master/src/dorkbox/util/Desktop.java#L216

If any of the above is eliminated, the `browseDirectory()` works properly.

**Comment by dorkbox** [comment]
Does F25 have access to `/usr/bin/gvfs-open`?

**Comment by dorkbox** [comment]
I've pushed the latest changes as well -- i've removed access via `GnomeVFS.gnome_vfs_url_show_with_env()` (it was buggy in other weird ways) and now it is pretty much exclusively via a shell command (which, is also buggy in weird ways, but I can at least work around some of them)

**Comment by kaloyan-raev** [comment]
```sh
$ ls -l /usr/bin/gvfs-open
-rwxr-xr-x 1 root root 277 Jul 19 18:26 /usr/bin/gvfs-open
```
