### ISSUE TITLE
Desktop.browseURL hangs

### ISSUE THREAD

**Issue by Djaler** [dorkbox/Utilities#4]
Calling Desktop.browseURL just freeze my program.

Looks like there are problem in java.awt.Desktop.browse() method.

OS - Debian 9
DE - KDE 5
Java - 8

**Comment by dorkbox** [comment]
There were some fixes for this that went out early December, which should have fixed this -- what version of SystemTray are you running?

**Comment by dorkbox** [comment]
Edit: I just saw your PR. Fixing now. Thanks! It will be included in the next release of SystemTray, v3.13
